version: '3.8'

services:
  phraseworks:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '8081:8081'
    env_file:
      - .env.local
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/logs:/app/backend/logs
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: phraseworks_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']

volumes:
  pgdata:
  redis_data:
