version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: backend_redis
    ports:
      - '6379:6379' # exposes Redis on localhost:6379
    volumes:
      - redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']

  mail:
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  redis_data:
